"""Initial schema

Revision ID: 8e81abede1f0
Revises: 
Create Date: 2026-07-23 07:12:36.409980

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e81abede1f0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workspaces',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('workspace_type', sa.Enum('PERSONAL', 'SHARED', name='workspacetype', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint('length(name) > 0', name=op.f('ck_workspaces_workspace_name_not_empty')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workspaces')),
    sa.UniqueConstraint('name', name='workspace_name_unique')
    )
    op.create_index('ix_workspaces_workspace_type', 'workspaces', ['workspace_type'], unique=False)
    op.create_table('documents',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('storage_filename', sa.String(length=255), nullable=False),
    sa.Column('storage_directory', sa.String(length=1000), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=False),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('document_metadata', sa.JSON(), nullable=True),
    sa.Column('status', sa.Enum('UPLOADED', 'PROCESSING', 'READY', 'FAILED', 'DELETED', 'ARCHIVED', name='documentstatus', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('processing_progress', sa.Integer(), nullable=False),
    sa.Column('processing_error', sa.String(length=1000), nullable=True),
    sa.Column('processing_details', sa.JSON(), nullable=True),
    sa.Column('chunk_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint('(page_count IS NULL) OR (page_count >= 0)', name=op.f('ck_documents_document_page_count_non_negative')),
    sa.CheckConstraint('processing_progress >= 0 AND processing_progress <= 100', name=op.f('ck_documents_document_processing_progress_valid')),
    sa.CheckConstraint('size_bytes >= 0', name=op.f('ck_documents_document_size_non_negative')),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_documents_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_documents'))
    )
    op.create_index('ix_documents_checksum', 'documents', ['checksum'], unique=False)
    op.create_index('ix_documents_status', 'documents', ['status'], unique=False)
    op.create_index('ix_documents_workspace_id', 'documents', ['workspace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_documents_workspace_id', table_name='documents')
    op.drop_index('ix_documents_status', table_name='documents')
    op.drop_index('ix_documents_checksum', table_name='documents')
    op.drop_table('documents')
    op.drop_index('ix_workspaces_workspace_type', table_name='workspaces')
    op.drop_table('workspaces')
    # ### end Alembic commands ###
